# Node.js with Angular

# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: $(calamityhub)
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build --prod
  displayName: 'npm install and build'
  
- task: Docker@2
  inputs:
    containerRegistry: 'Madrizz Container Registry'
    repository: 'kdds_flavora'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      latest

- task: AzureWebAppContainer@1
  displayName: 'Azure Web App on Container Deploy'
  inputs:
    azureSubscription: 'Azure subscription 1(899fce09-a777-4966-8a73-9b3aa35ee57d)'
    appName: 'flavorauidev'
    containers: 'madrizzdevregistry.azurecr.io/kdds_flavora:latest'